### ISSUE TITLE
header imports on FlxAPTBindings

### ISSUE THREAD

**Issue by pixelrevision** [ericjohnson/canabalt-ios#2]
when trying to add Flixel-ios to a seperate project these header imports appear to be missing from these 2 files:
FlxAPTBindings.h:
# import <OpenGLES/ES1/gl.h>
# import "FlxQuake.h"
# import "FlxSprite.h"
# import "FlxEmitter.h"

FlxAPTBindings.h:
# import "FlixelAPTBindings.h"

**Comment by ericjohnson** [comment]
Seems kind of odd that it would work correctly in the Canabalt project, but not in your own. Are you sure you've set everything up identically?

**Comment by pixelrevision** [comment]
There is a very good chance these headers are already imported somewhere in the game files so the compiler isn't complaining about them in the canabalt project.

The steps I used to create my project were:
1. Created a new window based application.
2. Added flixel-ios to the project.
3. Set the header search paths to flixel-ios folder.
4. Added the frameworks that were in the canabalt project.

When I compile it complains that FlixelAPTBindings.m can't find FlxQuake.  Adding an import to FlixelAPTBindings.m for it's header then generates another error about FlxQuake.  If I add the headers listed for FlixelAPTBindings.h the project then compiles with no errors.

On a side note I wanted to thank you guys for releasing this project.  I love flixel and am very excited to tinker around with it in objective-c.

**Comment by ericjohnson** [comment]
Glad you find the ios port of flixel useful!

I have no problem fixing this, I just want to do it in the most correct way possible. It sounds like you are doing everything correctly when creating the project, so there shouldn't be any problems there. But, I haven't been able to locate any other place within the project where FlxQuake.h is even imported. Try this for example:

cd ${PROJECT_ROOT}
grep -R FlxQuake.h *

The only place it pops up is in Flixel.h, which is where we'd expect it. Also, as long as you import Flixel.h, FlxQuake.h is imported _before_ FlxAptBinding.

Taking a closer look at things, it looks like the problem might be solved by simply adding '#import <Flixel/Flixel.h>' to the top of FlixelAPTBindings.m. This would actually make quite a bit of sense, since the Canabalt project imports Flixel.h within the precompiled header (Canabalt_Prefix.pch). Could you try making this change to FlixelAPTBindings.m, rather than the changes you listed to FlixelAPTBindings.h and FlixelAPTBindings.m, and let me know if that solves the issue for you?

**Comment by pixelrevision** [comment]
This make perfect sense.  
Importing <Flixel/Flixel.h> in FlixelAPTBindings.h takes care of the header.
I do still need to add '#import "FlixelAPTBindings.h"' to the implementation file, even if I import <Flixel/Flixel.h> in the app delegate.
